spring:
  application:
    name: graphql-kotlin-demo
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    actuator-metrics: true
  playground:
    cdn:
      version: latest
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
altair:
  enabled: true
  cdn:
    enabled: false
voyager:
  enabled: true
  cdn:
    enabled: false
graphql.playground:
  enabled: true
  cdn:
    enabled: false